/**
 * 与 vue-querybuilder dev/demoOptions 一致，保证默认行为一致
 */
export const defaultOptions = {
  showCombinatorsBetweenRules: false,
  showNotToggle: false,
  showCloneButtons: false,
  showLockButtons: false,
  showMuteButtons: false,
  showShiftActions: false,
  resetOnFieldChange: true,
  resetOnOperatorChange: false,
  autoSelectField: true,
  autoSelectOperator: true,
  autoSelectValue: true,
  addRuleToNewGroups: false,
  validateQuery: false,
  independentCombinators: false,
  listsAsArrays: false,
  enableDragAndDrop: false,
  disabled: false,
  debugMode: false,
  parseNumbers: false,
  justifiedLayout: false,
  showBranches: false,
  suppressStandardClassnames: false,
  useDateTimePackage: false,
} as const;

export const optionOrder = [
  'addRuleToNewGroups',
  'autoSelectField',
  'autoSelectOperator',
  'autoSelectValue',
  'showCombinatorsBetweenRules',
  'debugMode',
  'disabled',
  'enableDragAndDrop',
  'independentCombinators',
  'justifiedLayout',
  'listsAsArrays',
  'parseNumbers',
  'resetOnFieldChange',
  'resetOnOperatorChange',
  'showNotToggle',
  'showBranches',
  'showCloneButtons',
  'showLockButtons',
  'showMuteButtons',
  'showShiftActions',
  'suppressStandardClassnames',
  'useDateTimePackage',
  'validateQuery',
] as const;

export const optionLabels: Record<(typeof optionOrder)[number], string> = {
  addRuleToNewGroups: 'Add rule to new groups',
  autoSelectField: 'Auto-select field',
  autoSelectOperator: 'Auto-select operator',
  autoSelectValue: 'Auto-select value',
  showCombinatorsBetweenRules: 'Combinators between rules',
  debugMode: 'Debug mode',
  disabled: 'Disabled',
  enableDragAndDrop: 'Drag-and-drop enabled',
  independentCombinators: 'Independent combinators',
  justifiedLayout: 'Justified layout',
  listsAsArrays: 'Lists as arrays',
  parseNumbers: 'Parse numbers',
  resetOnFieldChange: 'Reset on field change',
  resetOnOperatorChange: 'Reset on operator change',
  showNotToggle: 'Show "not" toggle',
  showBranches: 'Show branches',
  showCloneButtons: 'Show clone buttons',
  showLockButtons: 'Show lock buttons',
  showMuteButtons: 'Show mute buttons',
  showShiftActions: 'Show shift actions',
  suppressStandardClassnames: 'Suppress standard classes',
  useDateTimePackage: 'Use date/time package',
  validateQuery: 'Use validation',
};
